<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>例外の原因 | 例外処理 | プログラミング言語の比較 | hydrocul のメモ</title>
<meta name="google-site-verification" content="uOXuLX4TAlCnMv26zOR30sGJVaZeWwaQLijOrxZiDyI" />
<link rel="stylesheet" href="https://raw.github.com/necolas/normalize.css/master/normalize.css" type="text/css" />
<link rel="stylesheet" href="../../common/css/page.css" type="text/css" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
<script src="https://rawgithub.com/adobe-webplatform/Snap.svg/master/dist/snap.svg-min.js"></script>
<script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
<script src="../../common/js/page.js"></script>
</head>
<body>

<div id="breadcrumb">
  <a href="../../programming_languages_diff/">プログラミング言語の比較</a> &gt; <a href="../../programming_languages_diff/exception/">例外処理</a> &gt; <span>例外の原因</span>
</div>
<div id="side-menu">
  <div id="side-menu-attention">
    このサイトは筆者(hydrocul)の個人メモの集合です。
  </div>
  <div id="side-menu-ls">
    <ul>
  <li><a href="../../programming_languages_diff/">プログラミング言語の比較</a>
    <ul>
      <li><a href="../../programming_languages_diff/exception/">例外処理</a>
        <ul>
          <li><a href="../../programming_languages_diff/exception/try.html">例外を捕捉する構文 (try / catch / finally)</a></li>
          <li><a href="../../programming_languages_diff/exception/throw.html">例外をスローする構文 (throw)</a></li>
          <li>例外の原因</li>
          <li><a href="../../programming_languages_diff/exception/class-hierarchy.html">例外クラス階層</a></li>
          <li><a href="../../programming_languages_diff/exception/checked.html">チェック例外と非チェック例外</a></li>
        </ul>
      </li>
    </ul>
  </li>
</ul>

  </div>
</div>

<div id="content">
  <h1 id="cause">例外の原因</h1>

<h2 id="ee0d33c">Java
<span class="article-date">2013/11/21</span></h2>

<p><code>Exception</code>などのクラスのコンストラクタには例外の原因となった例外を設定できるものが多い。コンストラクタになくても例外オブジェクトをいったん生成した後にメソッドで設定できる。</p>

<p>Signature:</p>

<pre><code>// java.lang.Throwable
Throwable initCause(Throwable cause);
</code></pre>

<p>メソッドで設定できるのは、これが Java 1.4 で導入された後付の機能のためだと思われる。
Java 1.4 以前はコンストラクタで <code>cause</code> を設定することができないので、そのときに作られた例外クラスに対しても <code>cause</code> を設定できるようにこのメソッドがある。このメソッドの返り値は例外の例外(<code>cause</code>)ではなく例外自身(<code>this</code>)でメソッドチェーンのためのもの。</p>

<h2 id="4975fba">PHP
<span class="article-date">2013/09/18</span></h2>

<p><code>Exception</code>クラスのコンストラクタの3つ目に例外の原因となった例外を指定することができる。ただ、スタックトレースを出力したときに
Javaのような例外の原因となった例外のスタックトレースまでは出力されないみたい。</p>

<p>例外 | PHPマニュアル
<a href="http://www.php.net/manual/ja/language.exceptions.php" target="_blank">http://www.php.net/manual/ja/language.exceptions.php</a></p>

</div>

<footer>
  <a href="../../">目次</a>
  <!-- Copyright &copy; 2012- @hydrocul All Rights Reserved. -->
</footer>

</body>
</html>
