<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>例外をキャッチする構文 | hydroculのメモ</title>
<meta name="google-site-verification" content="uOXuLX4TAlCnMv26zOR30sGJVaZeWwaQLijOrxZiDyI" />
<meta name="viewport" content="width=device-width,initial-scale=1.0" />
<link rel="stylesheet" href="https://raw.github.com/necolas/normalize.css/master/normalize.css" type="text/css" />
<link rel="stylesheet" href="../../common/css/page.css" type="text/css" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
<script src="https://rawgithub.com/adobe-webplatform/Snap.svg/master/dist/snap.svg-min.js"></script>
<script src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
<script src="../../common/js/page.js"></script>
</head>
<body class="res">

<div id="breadcrumb">
  <a href="../../">hydroculのメモ</a> &gt; <a href="../../programming_languages_diff/">プログラミング言語の比較</a> &gt; <a href="../../programming_languages_diff/exception/">例外処理</a> &gt; <span>例外をキャッチする構文</span>
</div>

<div id="content">
  <section>
<h1>例外をキャッチする構文
<span class="article-date">2021/01/18</span></h1>

<p>Java、Scala、JavaScript、CoffeeScript、PHP、C++、Perl、Ruby、Pythonでの例外をキャッチする構文。</p>

<section>
<h2>Java
<span class="article-date">2013/12/15</span></h2>

<pre><code class="prettyprint">try {
  ...;
} catch (FileNotFoundException e) {
  ...;
} catch (IOException e) {
  ...;
} finally {
  ...;
}
</code></pre>

<p>Java7から使える try-with-resources 構文では以下のように書ける。finally節を書かなくても try のカッコの中で生成したオブジェクトを確実にcloseしてくれる。この構文ではcatch節も書かずにtryのみも可能。</p>

<pre><code class="prettyprint">try (FileInputStream in = new FileInputStream(...)) {
  ...;
} catch (FileNotFoundException e) {
  ...;
} catch (IOException e) {
  ...;
}
</code></pre>

<p>同じくJava7からの機能では、catch節のカッコの中に複数の例外クラスを書ける。</p>

<pre><code class="prettyprint">try {
  ...;
} catch (IllegalArgumentException | IOException e) {
  ...;
}
</code></pre>

<p><code class="prettyprint">IOException | FileNotFoundException</code> のような一方が他方に含まれるような書き方はできないし、意味がない。</p>

<p>Java7から例外を再スローするときの型推論が改善されている。</p>

</section>
<section>
<h2>Scala
<span class="article-date">2017/01/11</span></h2>

<pre><code class="prettyprint">try {
  ...;
} catch {
  case e: IOException =&gt;
    ...;
  case e: FileNotFoundException =&gt;
    ...;
  case _: Exception =&gt; // 例外オブジェクトを変数で捕捉する必要がない場合
    ...;
  case e =&gt; // 例外オブジェクトの型を問わない場合
    ...;
} finally {
  ...;
}
</code></pre>

<p><code class="prettyprint">try</code>式は式なので、値を返す。<code class="prettyprint">try</code>節の中から例外がスローされなかった場合は、<code class="prettyprint">finally</code>節の中を実行した後に<code class="prettyprint">try</code>節の中の最後の式の値が<code class="prettyprint">try</code>式全体の返り値になる。</p>

<p><code class="prettyprint">catch</code>節の書き方は<a href="../control_flow/switch.html#scala"><code class="prettyprint">match</code>式</a>と同じ。</p>

</section>
<section>
<h2>JavaScript
<span class="article-date">2013/08/22</span></h2>

<pre><code class="prettyprint">try {
  ...;
} catch(ex) {
  ...;
} finally {
  ...;
}
</code></pre>

</section>
<section>
<h2>CoffeeScript
<span class="article-date">2013/08/22</span></h2>

<pre><code class="prettyprint">try
  ...
catch ex
  ...
finally
  ...
</code></pre>

</section>
<section>
<h2>PHP
<span class="article-date">2021/01/15</span></h2>

<pre><code class="prettyprint">try {
    ...;
} catch (Exception $e) {
    ...;
} catch (FooException | BarException $e) { // 複数の例外クラスをまとめてキャッチ
    ...;
} finally {
    ...;
}
</code></pre>

<p><code class="prettyprint">finally</code>節が書けるのはPHP 5.5以降。</p>

<p>複数の例外クラスをまとめてキャッチできるのはPHP 7.1以降。</p>

<p><a href="https://www.php.net/manual/en/language.exceptions.php">PHP: Exceptions - Manual</a></p>

</section>
<section>
<h2>C++
<span class="article-date">2013/09/11</span></h2>

<pre><code class="prettyprint">try {
  ...;
} catch (FooClass e) {
  ...;
} catch (BarClass e) {
  ...;
}
</code></pre>

</section>
<section>
<h2>Perl
<span class="article-date">2021/01/15</span></h2>

<pre><code class="prettyprint">eval {
    ...;
};
if ($@) {
    # 例外が発生した場合の処理
    ...;
}
</code></pre>

<p><code class="prettyprint">guard</code>または<code class="prettyprint">scope_guard</code>を使えば、他の言語のfinallyに相当することができる。</p>

<p><a href="https://perldoc.jp/docs/modules/Scope-Guard-0.20/Guard.pod">Scope::Guard - レキシカルスコープにおけるリソース管理 - perldoc.jp</a></p>

</section>
<section>
<h2>Ruby
<span class="article-date">2013/12/19</span></h2>

<pre><code class="prettyprint">begin
  ...
rescue
  ...
else
  ...
ensure
  ...
end
</code></pre>

<p><code class="prettyprint">rescue</code>節で例外オブジェクトを利用したい場合は、以下のように書く。</p>

<pre><code class="prettyprint">rescue =&gt; e
</code></pre>

<p>エラーメッセージは、 <code class="prettyprint">e.message</code> で取得できる。</p>

<p>スタックトレースを出力するには <code class="prettyprint">print e.backtrace.join(&quot;\n&quot;)</code> と書く。</p>

<p><code class="prettyprint">rescue</code>節で特定のクラスの例外だけを捕捉したい場合は、以下のように書く。</p>

<pre><code class="prettyprint">rescue ZeroDivisionError =&gt; e
</code></pre>

<p>例外クラス名はコンマ区切りで複数書ける。</p>

<p>捕捉する例外クラスのクラス名を省略すると、 <code class="prettyprint">StandardError</code> を捕捉するとみなされるので、<code class="prettyprint">StandardError</code> 以外の <code class="prettyprint">Exception</code> のインスタンスは捕捉されない。</p>

<p><code class="prettyprint">rescue</code>節自体は複数書くことができる。</p>

<p><code class="prettyprint">rescue</code>節の中では <code class="prettyprint">retry</code> と書くと、beginからやりなおしてくれる。これは他の言語にはあまりない機能である。</p>

<p><code class="prettyprint">else</code>節は例外が発生しなかった場合に<code class="prettyprint">ensure</code>節の前に実行される。これも他の言語にはあまりない機能である。</p>

</section>
<section>
<h2 id="python">Python
<span class="article-date">2021/01/18</span></h2>

<pre><code class="prettyprint">try:
  ...
except:
  ...
else:
  ...
finally:
  ...
</code></pre>

<p><code class="prettyprint">except</code>節で特定の例外クラスだけを捕捉したい場合は、次のように書く。</p>

<pre><code class="prettyprint">except HogeException:
</code></pre>

<p><code class="prettyprint">except</code>節で複数の例外クラスだけを捕捉したい場合は、次のように書く。</p>

<pre><code class="prettyprint">except (HogeException, PiyoException):
</code></pre>

<p><code class="prettyprint">except</code>節で例外インスタンスを捕捉したい場合は、次のように書く。</p>

<pre><code class="prettyprint">except HogeException as ex:
</code></pre>

<p><code class="prettyprint">except</code>節の中で同じ例外を再スローするには単に</p>

<pre><code class="prettyprint">raise
</code></pre>

<p>とだけ書く。</p>

<p><code class="prettyprint">else</code>節は<code class="prettyprint">try</code>節で例外がスローされずに完了した場合に実行される。例外がスローされた場合は<code class="prettyprint">except</code>節でキャッチされたかどうかに関わらず<code class="prettyprint">else</code>節は実行されない。</p>

<p><code class="prettyprint">finally</code>節は例外がスローされてもされなくても最後に必ず実行される。<code class="prettyprint">finally</code>節の前に<code class="prettyprint">return</code>、<code class="prettyprint">break</code>、<code class="prettyprint">continue</code>で脱出しようとしたときにも脱出直前に実行される。</p>

<p><a href="https://docs.python.org/3/tutorial/errors.html">8. Errors and Exceptions — Python 3.9.1 documentation</a></p>

</section>
</section>

</div>

<div id="side-menu">
  <div id="side-menu-attention">
    このサイトは個人メモの集合です。
  </div>
  <div class="ad">
<div class="adlabel">スポンサーリンク</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- page-box -->
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-4189452551543881"
     data-ad-slot="1792139650"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>

  <div id="side-menu-ls">
    <ul>
  <li><a href="../../programming_languages_diff/">プログラミング言語の比較</a>
    <ul>
      <li><a href="../../programming_languages_diff/exception/">例外処理</a>
        <ul>
          <li>例外をキャッチする構文</li>
          <li><a href="../../programming_languages_diff/exception/throw.html">例外をスローする構文</a></li>
          <li><a href="../../programming_languages_diff/exception/cause.html">例外の原因</a></li>
          <li><a href="../../programming_languages_diff/exception/class-hierarchy.html">例外クラス階層</a></li>
          <li><a href="../../programming_languages_diff/exception/checked.html">検査例外と非検査例外</a></li>
        </ul>
      </li>
    </ul>
  </li>
</ul>

  </div>
</div>

<footer>
  <a href="../../">HOME</a>
  <a href="../../policy.html">Privacy Policy</a>
  Copyright &copy; 2012- @hydrocul All Rights Reserved.
</footer>

</body>
</html>
