<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>例外を捕捉する構文 | 例外処理 | プログラミング言語の比較 | hydrocul のメモ</title>
<link rel="stylesheet" href="https://raw.github.com/necolas/normalize.css/master/normalize.css" type="text/css" />
<link rel="stylesheet" href="../../common/css/page.css" type="text/css" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
<script src="../../common/js/page.js"></script>
</head>
<body>

<div id="breadcrumb">
  <a href="../../programming_languages_diff/">プログラミング言語の比較</a> &gt; <a href="../../programming_languages_diff/exception/">例外処理</a> &gt; <span>例外を捕捉する構文</span>
</div>
<div id="side-menu">
  <div id="side-menu-attention">
    このサイトは筆者(hydrocul)の個人メモの集合です。
  </div>
  <div id="side-menu-ls">
    <ul>
  <li><a href="../../programming_languages_diff/">プログラミング言語の比較</a></li>
  <li>&gt; <a href="../../programming_languages_diff/exception/">例外処理</a></li>
  <li>&gt;&gt; <a href="../../programming_languages_diff/exception/checked.html">チェック例外と非チェック例外</a></li>
  <li>&gt;&gt; <a href="../../programming_languages_diff/exception/class-hierarchy.html">例外クラス階層</a></li>
  <li>&gt;&gt; <a href="../../programming_languages_diff/exception/throw.html">例外をスローする構文</a></li>
  <li>&gt;&gt; 例外を捕捉する構文</li>
</ul>

  </div>
</div>

<div id="content">
  <h1 id="try">例外を捕捉する構文</h1>

<h2 id="3cec5d1">Java
<span class="article-date">2013/08/22</span></h2>

<pre><code>try {
  ...;
} catch (FileNotFoundException e) {
  ...;
} catch (IOException e) {
  ...;
} finally {
  ...;
}
</code></pre>

<p>Java7から使える try-with-resources 構文では以下のように書ける。finally節を書かなくても try のカッコの中で生成したオブジェクトを確実にcloseしてくれる。この構文ではcatch節も書かずにtryのみも可能。</p>

<pre><code>try (FileInputStream in = new FileInputStream(...)) {
  ...;
} catch (FileNotFoundException e) {
  ...;
} catch (IOException e) {
  ...;
}
</code></pre>

<p>同じくJava7からの機能では、catch節のカッコの中に複数の例外クラスを書ける。</p>

<pre><code>try {
  ...;
} catch (IllegalArgumentException | IOException e) {
  ...;
}
</code></pre>

<p><code>IOException | FileNotFoundException</code> のような一方が他方に含まれるような書き方はできないし、意味がない。</p>

<h2 id="e66e9ef">Scala
<span class="article-date">2013/08/22</span></h2>

<pre><code>try {
  ...;
} catch {
  case e: IOException =&gt; ...;
  case e: FileNotFoundException =&gt; ...;
  case e =&gt; ...;
} finally {
  ...;
}
</code></pre>

<h2 id="9ebf3db">PHP
<span class="article-date">2013/08/22</span></h2>

<pre><code>try {
    ...;
} catch (Exception $e) {
    ...;
} finally {
    ...;
}
</code></pre>

<p>finally節が書けるのは PHP 5.5 以降。</p>

<h2 id="ee9152c">Ruby
<span class="article-date">2013/08/22</span></h2>

<pre><code>begin
  ...
rescue
  ...
else
  ...
ensure
  ...
end
</code></pre>

<p>rescue節で例外オブジェクトを利用したい場合は、以下のように書く。</p>

<pre><code>rescue =&gt; e
</code></pre>

<p>エラーメッセージは、 <code>e.message</code> で取得できる。</p>

<p>スタックトレースを出力するには <code>print e.backtrace.join("\n")</code> と書く。</p>

<p>rescue節で特定のクラスの例外を補足したい場合は、以下のように書く。</p>

<pre><code>rescue ZeroDivisionError =&gt; e
</code></pre>

<p>このようなクラス名を省略すると、 <code>StandardError</code> とみなされるので、
<code>StandardError</code> 以外の <code>Exception</code> のインスタンスは補足されない。</p>

<p>rescue節は複数書くことができる。</p>

<p>rescue節の中では <code>retry</code> と書くと、beginからやりなおしてくれる。これは他の言語にはあまりない機能である。</p>

<h2 id="1add679">Python
<span class="article-date">2013/08/22</span></h2>

<pre><code>try:
  ...
except:
  ...
finally:
  ...
</code></pre>

<p>except節で例外オブジェクトを扱う場合は、 <code>except ex:</code> のように書く。</p>

<p>特定の例外クラスだけexcept節で扱う場合は、 <code>except HogeException:</code>
または <code>except HogeException, ex:</code> のように書く。</p>

<p>except節の中で同じ例外を再スローするには単に <code>raise</code> とだけ書く。</p>

<h2 id="ed3e43f">JavaScript
<span class="article-date">2013/08/22</span></h2>

<pre><code>try {
  ...;
} catch(ex){
  ...;
} finally {
  ...;
}
</code></pre>

<h2 id="587f858">CoffeeScript
<span class="article-date">2013/08/22</span></h2>

<pre><code>try
  ...
catch ex
  ...
finally
  ...
</code></pre>


</div>

<footer>
  <a href="../../">目次</a>
  <!-- Copyright &copy; 2012- @hydrocul All Rights Reserved. -->
</footer>

</body>
</html>
