<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>例外を捕捉する構文 (try / catch / finally) | 例外処理 | プログラミング言語の比較 | hydroculのメモ</title>
<meta name="google-site-verification" content="uOXuLX4TAlCnMv26zOR30sGJVaZeWwaQLijOrxZiDyI" />
<meta name="viewport" content="width=device-width,initial-scale=1.0" />
<link rel="stylesheet" href="https://raw.github.com/necolas/normalize.css/master/normalize.css" type="text/css" />
<link rel="stylesheet" href="../../common/css/page.css" type="text/css" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
<script src="https://rawgithub.com/adobe-webplatform/Snap.svg/master/dist/snap.svg-min.js"></script>
<script src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
<script src="../../common/js/page.js"></script>
</head>
<body class="res">

<div id="breadcrumb">
  <a href="../../">hydroculのメモ</a> &gt; <a href="../../programming_languages_diff/">プログラミング言語の比較</a> &gt; <a href="../../programming_languages_diff/exception/">例外処理</a> &gt; <span>例外を捕捉する構文 (try / catch / finally)</span>
</div>

<div id="content">
  <h1 id="try">例外を捕捉する構文 (try / catch / finally)</h1>

<h2 id="897da8a">C++
<span class="article-date">2013/09/11</span></h2>

<pre><code>try {
  ...;
} catch (FooClass e) {
  ...;
} catch (BarClass e) {
  ...;
}
</code></pre>

<h2 id="7655c41">Java
<span class="article-date">2013/12/15</span></h2>

<pre><code>try {
  ...;
} catch (FileNotFoundException e) {
  ...;
} catch (IOException e) {
  ...;
} finally {
  ...;
}
</code></pre>

<p>Java7から使える try-with-resources 構文では以下のように書ける。finally節を書かなくても try のカッコの中で生成したオブジェクトを確実にcloseしてくれる。この構文ではcatch節も書かずにtryのみも可能。</p>

<pre><code>try (FileInputStream in = new FileInputStream(...)) {
  ...;
} catch (FileNotFoundException e) {
  ...;
} catch (IOException e) {
  ...;
}
</code></pre>

<p>同じくJava7からの機能では、catch節のカッコの中に複数の例外クラスを書ける。</p>

<pre><code>try {
  ...;
} catch (IllegalArgumentException | IOException e) {
  ...;
}
</code></pre>

<p><code>IOException | FileNotFoundException</code> のような一方が他方に含まれるような書き方はできないし、意味がない。</p>

<p>Java7から例外を再スローするときの型推論が改善されている。</p>

<h2 id="df8f7b8">Scala
<span class="article-date">2014/04/02</span></h2>

<pre><code>try {
  ...;
} catch {
  case e: IOException =&gt; ...;
  case e: FileNotFoundException =&gt; ...;
  case e =&gt; ...;
} finally {
  ...;
}
</code></pre>

<p><code>try</code>式は式なので、値を返す。<code>try</code>節の中から例外がスローされなかった場合は、
<code>finally</code>節の中を実行した後に<code>try</code>節の中の最後の式の値が<code>try</code>式全体の返り値になる。</p>

<h2 id="8a39adb">PHP
<span class="article-date">2014/05/26</span></h2>

<pre><code>try {
    ...;
} catch (Exception $e) {
    ...;
} finally {
    ...;
}
</code></pre>

<p><code>finally</code>節が書けるのはPHP5.5以降。</p>

<p>例外 | PHP Manual<br />
<a href="http://php.net/manual/ja/language.exceptions.php" target="_blank">http://php.net/manual/ja/language.exceptions.php</a></p>

<h2 id="python">Python
<span class="article-date">2013/08/22</span></h2>

<pre><code>try:
  ...
except:
  ...
finally:
  ...
</code></pre>

<p><code>except</code>節で例外オブジェクトを利用したい場合は、以下のように書く。</p>

<pre><code>except ex:
</code></pre>

<p><code>except</code>節で特定の例外クラスだけを捕捉したい場合は、以下のように書く。</p>

<pre><code>except HogeException:

# または
except HogeException, ex:
</code></pre>

<p><code>except</code>節の中で同じ例外を再スローするには単に</p>

<pre><code>raise
</code></pre>

<p>とだけ書く。</p>

<h2 id="dee92b0">Ruby
<span class="article-date">2013/12/19</span></h2>

<pre><code>begin
  ...
rescue
  ...
else
  ...
ensure
  ...
end
</code></pre>

<p><code>rescue</code>節で例外オブジェクトを利用したい場合は、以下のように書く。</p>

<pre><code>rescue =&gt; e
</code></pre>

<p>エラーメッセージは、 <code>e.message</code> で取得できる。</p>

<p>スタックトレースを出力するには <code>print e.backtrace.join("\n")</code> と書く。</p>

<p><code>rescue</code>節で特定のクラスの例外だけを捕捉したい場合は、以下のように書く。</p>

<pre><code>rescue ZeroDivisionError =&gt; e
</code></pre>

<p>例外クラス名はコンマ区切りで複数書ける。</p>

<p>捕捉する例外クラスのクラス名を省略すると、 <code>StandardError</code> を捕捉するとみなされるので、
<code>StandardError</code> 以外の <code>Exception</code> のインスタンスは捕捉されない。</p>

<p><code>rescue</code>節自体は複数書くことができる。</p>

<p><code>rescue</code>節の中では <code>retry</code> と書くと、beginからやりなおしてくれる。これは他の言語にはあまりない機能である。</p>

<p><code>else</code>節は例外が発生しなかった場合に<code>ensure</code>節の前に実行される。これも他の言語にはあまりない機能である。</p>

<h2 id="43536fc">Perl
<span class="article-date">2013/09/11</span></h2>

<pre><code>eval {
    ...;
};
if ($@) {
    # 例外が発生した場合の処理
    ...;
}
</code></pre>

<h2 id="7bf0076">JavaScript
<span class="article-date">2013/08/22</span></h2>

<pre><code>try {
  ...;
} catch(ex){
  ...;
} finally {
  ...;
}
</code></pre>

<h2 id="afe2a20">CoffeeScript
<span class="article-date">2013/08/22</span></h2>

<pre><code>try
  ...
catch ex
  ...
finally
  ...
</code></pre>

</div>

<div id="side-menu">
  <div id="side-menu-attention">
    このサイトは筆者(hydrocul)の個人メモの集合です。すべてのページは永遠に未完成です。
  </div>
  <div id="side-menu-ls">
    <ul>
  <li><a href="../../programming_languages_diff/">プログラミング言語の比較</a>
    <ul>
      <li><a href="../../programming_languages_diff/exception/">例外処理</a>
        <ul>
          <li>例外を捕捉する構文 (try / catch / finally)</li>
          <li><a href="../../programming_languages_diff/exception/throw.html">例外をスローする構文 (throw)</a></li>
          <li><a href="../../programming_languages_diff/exception/cause.html">例外の原因</a></li>
          <li><a href="../../programming_languages_diff/exception/class-hierarchy.html">例外クラス階層</a></li>
          <li><a href="../../programming_languages_diff/exception/checked.html">チェック例外と非チェック例外</a></li>
        </ul>
      </li>
    </ul>
  </li>
</ul>

  </div>
</div>

<footer>
  <a href="../../">目次</a>
  <!-- Copyright &copy; 2012- @hydrocul All Rights Reserved. -->
</footer>

</body>
</html>
